### ISSUE TITLE
SQLite engine expiration dependency

### ISSUE THREAD

**Issue by velosipedist** [nette/caching#17]
Does it planned to implement?

**Comment by dg** [comment]
I don't understand what you mean? Btw, for questions use forum please.

**Comment by velosipedist** [comment]
SQLite storage has just [tags](https://github.com/nette/caching/blob/master/src/Caching/Storages/SQLiteStorage.php#L82) dependency support. While file storage, for example, has also expiration dependency feature. 

If there is no polans to implement, i can try to do this myself at near future.

**Comment by milo** [comment]
@velosipedist I would like this to be implemented too. I will need it in summer and I'm planning to do it, but would be great if you can give a try.

There is a few months old https://github.com/milo/nette-caching/commit/dae466cd3f9dc5b0a755ee8a058865d400d97a2d quick&nasty implementation. Unit tests and performance measurements needed. And some simplification in `clean()` too I guess.

**Comment by velosipedist** [comment]
@milo well, i can try, cause i have my personal uinterests here too :) But not closer han end of February.
