### ISSUE TITLE
Malformed journal file 'btfj.dat'

### ISSUE THREAD

**Issue by janreges** [nette/caching#18]
Hello,

I use Nette 2.2.7. Today my production project totally crashed and doesn't work after error "Malformed journal file 'btfj.dat'".

My btfj.dat has 4 382 720 bytes after that error. In this file, there was no MAGIC header.

Here is first 5 000 bytes of broken btfj.dat: http://nette.nahledwebu.cz/btfj-error.dat
Here is first 5 000 bytes of btfj.dat, when is OK: http://nette.nahledwebu.cz/btfj-error.dat

This bug occurs probably after cleanTags() calls.

I've made dirty workaround in our project. After that exception catched, I delete btfj.dat, call clean(Cache:ALL) and send an e-mail to admin about that.

This bug is very dangerous - when occurs, whole website is broken and is required to manually fix it.

**Comment by milo** [comment]
This is probably very similar to #11. Sorry about that, it is very difficult to find it. You may try SQLiteStorage which is a bit slower but supports tags too,

**Comment by janreges** [comment]
@dg, @JakubOnderka, @milo: What do you think about my expected behaviour?

When problem with btfj.dat consistency occurs, there have to be some kind of auto-fix mechanism.

It's not acceptable, that this inconsistency permamently crashed whole website, and manual-fix is required.

Expected behaviour:

1) Layer above journal catch an exception about fatal btfj.dat inconsistency

2) File btfj.dat have to be deleted (or renamed to btfj.[datetime].dat for debug purposes)

3) Whole journaled cache have to be deleted, because from this moment, cleaning by tags/properties doesn't work properly (relations has been deleted with btfj.dat)

4) In production, critical error have to be writen (by configuration, it is sent to admin) .. in development, an exception can be thrown.

Result: this inconsistency doesn't affect production website, cache warmed herself and admin can report an issue with renamed btfj.dat.

Does that make sense? I know, it's not so clean, but it's better than wait few next months/years for bugfix. I love FileJournal, except this issue :)

It would be fine to handle it only internally in FileJournal, but FileJournal has no dependency to cache storage (what's right).

**Comment by milo** [comment]
Personally, I would drop whole FileJournal completely. It is a dead code without maintainer. After the #17 SQLiteStorage maybe the adequate replacement.

**Comment by dg** [comment]
@milo :+1:

**Comment by dg** [comment]
Btw SqliteJournal is here https://github.com/nette/caching/blob/f07302949bed1cc7a1aa619d8ca0ec495a28a9c5/src/Caching/Storages/SqliteJournal.php

**Comment by JanTvrdik** [comment]
@milo Maintainer would not help if he's unable to reproduce the issue. Few months ago I spent a couple of hours trying to reproduce the issue but the only reproducible issue I found was https://github.com/nette/caching/issues/12

**Comment by milo** [comment]
@JanTvrdik Maintainer would help if he would confirm he cannot reproduce it. But seems to me @JakubOnderka is not interested anymore.

I really don't want to hate somebody and I have understanding for such situations. It is just situation which should be solved somehow.

**Comment by hrach** [comment]
Personally, I would love (have a plan) to review this. But no estimate when :-)

**Comment by pavolbiely** [comment]
I confirm. We are experiencing this issue very often using tags otherwise it works fine.

**Comment by dg** [comment]
Recommended solution: use `nette/cache` version 2.4

**Comment by dg** [comment]
FileJournal is not maintained anymore, use SQLiteJournal.
