### ISSUE TITLE
CacheExtension: PDOException: could not find driver

### ISSUE THREAD

**Issue by alesculek** [nette/caching#24]
When I used "nette/nette": "~2.3", in my project it installed nette/caching as dependency on this revision https://github.com/nette/caching/commit/a89c504a9ce6a21d4e70af18dbb4c31a7a534d11

And when i tried to run project there was exception: PDOException: could not find driver,
with path to temp/cache/journal.s3db (file really not exists)

After this command everything work ok:
vendor/nette/caching$ (master) git reset --hard HEAD~1
HEAD is now at 47bd309 typo in class name

PHP	5.6.4-4ubuntu6
Tracy	2.3.2
Server	Apache/2.4.10 (Ubuntu)
Nette Framework	2.3-dev

**Comment by milo** [comment]
Due to #11, #18, default storage has been changed to a89c504a9ce6a21d4e70af18dbb4c31a7a534d11. Enable the pdo_sqlite extension in php.ini. If you cannot, chage the cache journal back to FileJournal in config.neon.

**Comment by alesculek** [comment]
Ok, thanks for your reply. I tought that there is a bc break, but a haven't really loaded pdo_sqlite :)
Thanks.

**Comment by milo** [comment]
I realized, that you are using `~2.3` somehow with minimal stability RC, because mentioned commit is in `2.4.0-RC` only. You can use `~2.3.0` to keep 2.3 branch.

If someone prefers to keep buggy FileJournal for any reason, update your `config.neon` by:
```neon
services:
    cache.journal: Nette\Caching\Storages\FileJournal(%tempDir%)
```

**Comment by alesculek** [comment]
No, I have used ~2.3 with minimum stability dev
