### ISSUE TITLE
SQLiteJournal: General error: 1 too many SQL variables	

### ISSUE THREAD

**Issue by hranicka** [nette/caching#25]
I've switched our project to Nette\Caching v2.4 due to another bug (issue #18).

But today, an application has failed with `PDOException #HY000 SQLSTATE[HY000]: General error: 1 too many SQL variables`.

I can't provide error log in RAW HTML output (proprietaly real application), but I can part of Stack Trace as image:

![6sjstvs](https://cloud.githubusercontent.com/assets/3034538/8706561/a63a24ae-2b30-11e5-98f7-fd52dfc21083.png)

**Comment by hranicka** [comment]
Does anybody know what's the problem? Is it too many records with tags?

**Comment by dg** [comment]
@milo why is not [here](https://github.com/nette/caching/blob/46491438f59c49ba4b1658265ef21a601f858c50/src/Caching/Storages/SQLiteJournal.php#L106) není `DELETE FROM tags WHERE tag IN `?

**Comment by hranicka** [comment]
@dg [There](https://github.com/nette/caching/blob/46491438f59c49ba4b1658265ef21a601f858c50/src/Caching/Storages/SQLiteJournal.php#L106) can't be delete because we must return deleted keys, e.g. for [files deleting in FileStorage](https://github.com/nette/caching/blob/master/src/Caching/Storages/FileStorage.php#L301).

So I've replaced "too many SQL variables" with subquery in pull request #26 (with test for the bug).

Please, can you see it? It's a critical bug, we have problems on more projects now.

P. S. Sorry for rebases above (spam)...

**Comment by dg** [comment]
Btw this change probably makes clean non atomic

**Comment by hranicka** [comment]
Do you mean that we must load keys and delete records in one transaction?

If we begin transaction before data fetching will be it OK in SQLite?

**Comment by dg** [comment]
Pprobably yes and the transaction should be open via `BEGIN IMMEDIATE`.

**Comment by milo** [comment]
@hranicka Thanks for fixing this.
