### ISSUE TITLE
Wrong class names for storages

### ISSUE THREAD

**Issue by petrknap** [nette/caching#48]
Please change class names of storages, because:

- **Memcache**Storage doesn't exist
- **Memcached**Storage doesn't support memcached extension
- **NewMemcached**Storage... Shame on the author of this class name

Thanks for your time, I hope that you will change it and I will never find anything like `NewNewMemchachedStorage` after another memory cache extension will be released.

**Comment by hrach** [comment]
I'm the author and I was "forced" to name it like this :) Please read the *whole* thread here:
https://github.com/nette/caching/pull/38

**Comment by hrach** [comment]
This was done because it would be a BC break. I think it would be correct rename it for Nette 3.0.

**Comment by TomasVotruba** [comment]
Hi @petrknap, how would you like to see those classes named then?

@hrach Thanks for reference!

**Comment by petrknap** [comment]
@hrach That feeling when you know how to do it right, but they say BC. I'm looking forward to Nette 3 if this BC terror will be removed. :)

@TomasVotruba Simply - **Memcache**Storage for **memcache** extension (currently MemcachedStorage) and **Memcached**Storage for **memcached** extension (currently NewMemcachedStorage).

**Comment by dg** [comment]
@petrknap and what about compatibility?

**Comment by petrknap** [comment]
@dg Compatibility is problem, I must admit it. But this change can be part of new huge release (Nette 3, as @hrach mentioned).  It is clean and logical - I can't imagine better reason for Nette 3 release than removing BC in cases when BC supports bad practices.

**Comment by dg** [comment]
It should in one release trigger warning, in second release it can be changed.
