### ISSUE TITLE
Storage accept callback for atomic operation

### ISSUE THREAD

**Issue by h4kuna** [nette/caching#57]
If i want implement apcu by IStorage then apcu has own atomic method, whose works fine. But interface of IStorage does not allow use callback for [apcu_entry](https://www.php.net/manual/en/function.apcu-entry.php).

For this moment locking solves cache and i can't to use native lock from strorage. Same problem is with redis where in implementation is useful callback.

I understand this is probably BC break. I try to create [implementation where](/h4kuna/cache/commit/e7dea600d7cc4d07f81d6912dc1645cd23db41c0) i add new interfaces ISelfLock, ISimpleStorage and IStorage has still same api.

I [made little test](/h4kuna/cache#selflock-storage) where files blocking concurrent processes while apcu with ISelfLock does not do it.

[Here is other info](https://forum.nette.org/cs/32136-api-istorage-mi-nedovoluje-pouzit-nativni-atomicitu-pomoci-apcu-entry) (in czech)

**Comment by dg** [comment]
Do you know how it works in Redis?

**Comment by h4kuna** [comment]
I didn't implement but, @forrest79 could you describe it.

**Comment by forrest79** [comment]
I think, that Redis is not corresponding to this issue. We just implemented passive locking via `SETNX` and `BLPOP` (something like this https://github.com/ionelmc/python-redis-lock in PHP) but it's sometimes crashed under heavy load.

**Comment by dg** [comment]
So for redis is best solution lock() & release()

**Comment by forrest79** [comment]
I thing yes. But what is describing h4kuna can be really handy. On smaller sites, I'm using APCu as cache and I want to use build-in atomic fetch method, but it means, that I can't use `Nette/Cache`

**Comment by dg** [comment]
I understand that, but I needed to verify info about Redis.

**Comment by forrest79** [comment]
I don't know about Redis cache/lock, that is not comatible with current Cache implementation.

**Comment by h4kuna** [comment]
Redis has lock, but by default for few seconds and after automatically unlock.

After few year, I think the lock behavior is better like wraper above cache.

I created own [Lock](https://github.com/h4kuna/critical-cache/blob/main/src/Lock.php) interface. And usage is in [Cache](https://github.com/h4kuna/critical-cache/blob/main/src/Cache.php#L99). Where try get data from cache, if value is null, than create lock for critical section, try read once more and if data still null then build cache.
