### ISSUE TITLE
Pascal Case for constants

### ISSUE THREAD

**Issue by Kocicak** [nette/caching#67]
https://github.com/nette/caching/commit/8bf7455878eca4ce74083d0fc52b722e6c89ff51

Hi, in version 3.1.3, constant NAMESPACE_SEPARATOR disappeared and is no longer available. And also backward compatible name has not been added. Can you please add upper snake case constant?

Also, why Pascal Case for class constants? This is opposed to PSR-12, which you claim, that Nette follows: https://doc.nette.org/en/contributing/coding-standard. PSR-12 states that PSR-1 must be adhered. And PSR-1 states that "Class constants MUST be declared in all upper case with underscore separators". So why is Nette not following PSR-12 coding standard?

EDIT: also, why is backward-incompatible change released as patch version and not major version?

Thanks.

**Comment by dg** [comment]
The reason is that PascalCase constants look better in the code.

**Comment by petrparolek** [comment]
> The reason is that PascalCase constants look better in the code. I've fixed the documentation.

zase nesmyslné novinky! Nechceš zavádět místo dlouhých názvů zkratky? :D Stále nechápu modu!Programování není o modních výstřelcích ale o standardech.

**Comment by dg** [comment]
@Kocicak  I won't miss a prick like you around here. Bye-bye.

@petrparolek Please use English

**Comment by Kocicak** [comment]
Ok, so to make the code more pretty, you now have all constants defined twice. Once with upper snake case, once with pascal case. Not to mention when using those constants, IDE will offer you every constant twice, in each case. I wonder which case will everyone following PSR-1 choose :)

Can't help it, but the code doesn't seem prettier or improved in any way.

**Comment by milo** [comment]
> you now have all constants defined twice

BC?

> will offer you every constant twice

Improvable by `@deprecated`?

> which case will everyone following PSR-1

Probably blindly the upper case? With a small prayer everytime?

> Can't help it, but the code doesn't seem prettier or improved in any way.

Try to use it month or two. Personally, I would never came back. Good code is readable like story. Much better with pascal case constants. One can focus on logic, not syntax.

> just change in new patch version

without BC break

**Comment by Kocicak** [comment]
> Improvable by `@deprecated`?

IDE will still offer you two variants, one will be struck-through. If I want to comply with PSR-1 in my project, I will use deprecated ones and IDE will mark those usages as errors / warnings. Not a great idea.

> Try to use it month or two. Personally, I would never came back. Good code is readable like story. Much better with pascal case constants. One can focus on logic, not syntax.

Well, code is not a story. Logic tells you that constants are upper case, so when you see it, you don't need to focus on syntax. I think this is highly subjective, but when I read code with pascal case constants, It seems like I'm looking at static method call. So now I have to focus on syntax to know that this is not static method call, but poorly named constant. The resulting effect is opposite, readability is actually worse.

> without BC break

But there was a BC break before it got fixed, wasn't?

**Comment by dg** [comment]
BTW Capitalised class constants are leaving PHP itself with the advent of enums https://www.php.net/manual/en/language.enumerations.basics.php

**Comment by mabar** [comment]
> If I want to comply with PSR-1 in my project, I will use deprecated ones

PSR-1 states that "Class constants MUST be declared in all upper case with underscore separators." It is about declaration, not about usage.

> when I read code with pascal case constants, It seems like I'm looking at static method call

Then you will probably have the same problem with enum cases. [Enums RFC](https://wiki.php.net/rfc/enumerations) uses PascalCase. e.g. [Symfony](https://symfony.com/doc/current/reference/forms/types/enum.html#example-usage) and [Monolog](https://github.com/Seldaek/monolog/blob/60ad5183b5e5d6c9d4047e9f3072d36071dcc161/src/Monolog/Level.php#L36) already do the same.

Also all methods should be camelCase anyway, according to PSR-1, don't they?

> But there was a BC break before it got fixed, wasn't?

Anything marked `@internal` can be removed without notice.

**Comment by mabar** [comment]
Oh, one more thing. Seems like the [PSR-12 follow up](https://github.com/php-fig/per-coding-style/blob/b5cac843d433745fe72aa3fd43fa6a86199bb289/spec.md#example) may be okay with PascalCase too. 

They state that: "This example encompasses some rules below as a quick overview" and then use `use const Vendor\Package\{ConstantA, ConstantB, ConstantC};` in example.

They are now even discussing [recommendation PascalCase](https://github.com/php-fig/per-coding-style/pull/7/files#diff-bc6661da34ecae62fbe724bb93fd69b91a7f81143f2683a81163231de7e3b545R1107). (even though CamelCase is miscorrectly used in PR)
