### ISSUE TITLE
Version 3.1.3 is not PHP < 8.0 compatible

### ISSUE THREAD

**Issue by jankonas** [nette/caching#68]
Version 3.1.3 declares PHP compatibility as >=7.2 <8.2 but uses nullsafe operator (which is PHP 8.0+):

https://github.com/nette/caching/blob/v3.1.3/src/Bridges/CacheLatte/Nodes/CacheNode.php#L39

Is PR with removing nullsafe operator welcome?

**Comment by dg** [comment]
It is code for Latte 3 which requires PHP 8.
